# Generated by Django 6.0.6 on 2026-09-01 07:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_api', '0028_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('APPRENTICE', 'Apprentice')], db_index=True, default='FULL_TIME', max_length=20)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Pay per hour. Payroll skips anyone whose rate is unset.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=0, help_text='Expected hours a week. Reference only; payroll pays attendance, not this.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_total', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit agreed with this staff member.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_weekly', models.DecimalField(decimal_places=2, default=0, help_text="Scheduled weekly recovery. Never recovers more than the balance outstanding or the week's earnings.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['staff__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='staff_profile_hourly_rate_not_negative'), models.CheckConstraint(condition=models.Q(('deposit_total__gte', 0)), name='staff_profile_deposit_total_not_negative'), models.CheckConstraint(condition=models.Q(('deposit_weekly__gte', 0)), name='staff_profile_deposit_weekly_not_negative'), models.CheckConstraint(condition=models.Q(('weekly_hours__gte', 0)), name='staff_profile_weekly_hours_not_negative')],
            },
        ),
    ]
