# Generated by Django 6.0.6 on 2026-09-01 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0028_order_discount'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SELF', 'Recorded by the staff member'), ('OWNER', 'Recorded by the boutique owner')], db_index=True, default='SELF', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('original_check_in', models.DateTimeField(blank=True, null=True)),
                ('original_check_out', models.DateTimeField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrected', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['staff', '-date'], name='attendance_staff_day'), models.Index(fields=['date'], name='attendance_day')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('staff',), name='attendance_one_open_session_per_staff'), models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_out__gte', models.F('check_in')), _connector='OR'), name='attendance_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('minutes__isnull', True), ('minutes__gte', 0), _connector='OR'), name='attendance_minutes_not_negative')],
            },
        ),
    ]
