# Generated by Django 6.0.6 on 2026-09-02 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0028_order_discount'),
        ('staff', '0002_attendancesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name_snapshot', models.CharField(max_length=150)),
                ('role_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('review_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom period')], db_index=True, default='MONTHLY', max_length=12)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('productivity_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Needs significant improvement'), (2, 'Needs improvement'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Outstanding')], null=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Needs significant improvement'), (2, 'Needs improvement'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Outstanding')], null=True)),
                ('timeliness_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Needs significant improvement'), (2, 'Needs improvement'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Outstanding')], null=True)),
                ('attendance_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Needs significant improvement'), (2, 'Needs improvement'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Outstanding')], null=True)),
                ('reliability_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Needs significant improvement'), (2, 'Needs improvement'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Outstanding')], null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvement_areas', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('kpi_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalised'), ('ACKNOWLEDGED', 'Acknowledged by staff')], db_index=True, default='DRAFT', max_length=14)),
                ('reviewer_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_written', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['-period_start', 'staff_name_snapshot'],
                'indexes': [models.Index(fields=['staff', '-period_start'], name='review_staff_period'), models.Index(fields=['status', '-period_start'], name='review_status_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='review_period_ends_after_it_starts'), models.UniqueConstraint(fields=('staff', 'period_start', 'period_end', 'review_type'), name='review_unique_per_staff_period')],
            },
        ),
    ]
