# Generated by Django 6.0.6 on 2026-09-08 05:17

import apps.staff.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0032_finalise_roles'),
        ('staff', '0004_attendance_survives_staff_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN card'), ('DRIVING_LICENCE', 'Driving licence'), ('VOTER_ID', 'Voter ID'), ('BANK_PASSBOOK', 'Bank passbook'), ('CONTRACT', 'Signed contract'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('number', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('file', models.FileField(max_length=500, upload_to=apps.staff.models.upload_to_staff_documents)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm_api.tailor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['staff', 'kind'], name='staff_staff_staff_i_4f54df_idx')],
            },
        ),
    ]
