# Generated by Django 6.0.6 on 2026-09-08 05:37

import apps.staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=models.FileField(max_length=500, storage=apps.staff.models.staff_document_storage, upload_to=apps.staff.models.upload_to_staff_documents),
        ),
    ]
