# Generated by Django 6.0.6 on 2026-09-08 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0032_finalise_roles'),
        ('design_studio', '0018_designer_phone'),
        ('staff', '0006_alter_staffdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='design_studio.designer'),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm_api.tailor'),
        ),
        migrations.AddIndex(
            model_name='staffdocument',
            index=models.Index(fields=['designer', 'kind'], name='staff_staff_designe_24d137_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('designer__isnull', True), ('staff__isnull', False)), models.Q(('designer__isnull', False), ('staff__isnull', True)), _connector='OR'), name='staff_document_belongs_to_exactly_one'),
        ),
    ]
