# Generated by Django 6.0.6 on 2026-06-23 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city_region', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='Walk In', max_length=50)),
                ('customer_type', models.CharField(default='Women', max_length=50)),
                ('garment_type', models.CharField(default='Lehenga', max_length=100)),
                ('neckline_style', models.CharField(blank=True, max_length=100, null=True)),
                ('sleeve_style', models.CharField(blank=True, max_length=100, null=True)),
                ('back_style', models.CharField(blank=True, max_length=100, null=True)),
                ('length_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('silhouette', models.CharField(blank=True, max_length=100, null=True)),
                ('embellishments', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern_style', models.CharField(blank=True, max_length=100, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_requirements', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_communication', models.CharField(default='WhatsApp', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_images', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_preferences', to='crm_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FabricSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boutique_fabric', models.BooleanField(default=True)),
                ('fabric_name', models.CharField(max_length=150)),
                ('fabric_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('uploaded_fabric_images', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_selections', to='crm_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('additional_measurements', models.JSONField(blank=True, default=dict)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='crm_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('order_status', models.CharField(default='Confirmed', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fabric_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('embroidery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customization_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tailoring_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('packaging_handling', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_api.customer')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm_api.tailor')),
            ],
        ),
    ]
