# Generated by Django 6.0.6 on 2026-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('garment_type', models.CharField(max_length=100)),
                ('neckline_style', models.CharField(blank=True, max_length=100, null=True)),
                ('sleeve_style', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('is_boutique', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
