# Generated by Django 6.0.6 on 2026-07-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_boutiquedesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_orders', to='crm_api.tailor'),
        ),
        migrations.AddField(
            model_name='tailor',
            name='role',
            field=models.CharField(default='Tailor', max_length=50),
        ),
    ]
