# Generated by Django 6.0.6 on 2026-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_order_courier_service_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
