# Generated by Django 6.0.6 on 2026-07-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0006_order_advance_paid_order_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_role', models.CharField(max_length=50)),
                ('recipient_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
