# Generated by Django 6.0.6 on 2026-07-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0008_order_completed_garment_image_order_tailor_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stage_images/')),
                ('completed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='crm_api.order')),
            ],
        ),
    ]
