# Generated by Django 6.0.6 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0009_orderstagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scaleezy Atelier', max_length=255)),
                ('address', models.TextField(default='123 Atelier Way, Fashion District')),
                ('phone', models.CharField(default='+91 9999999999', max_length=50)),
                ('email', models.EmailField(default='contact@scaleezy.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutique_logos/')),
            ],
        ),
    ]
