# Generated by Django 6.0.6 on 2026-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0013_measurementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
