# Generated by Django 6.0.6 on 2026-07-23 05:38

import crm_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0014_order_master_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='workflow_config',
            field=models.JSONField(blank=True, default=crm_api.models.get_default_workflow),
        ),
        migrations.AddField(
            model_name='order',
            name='current_stage_key',
            field=models.CharField(default='created', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='production_status',
            field=models.CharField(default='NOT_STARTED', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm_api.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=100)),
                ('stage_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='NOT_STARTED', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('sequence', models.IntegerField(default=0)),
                ('sla_hours', models.IntegerField(default=24)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm_api.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_api.tailor')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
