# Generated by Django 6.0.6 on 2026-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0015_boutiquesettings_workflow_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(db_index=True, default='Women', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_stage_key',
            field=models.CharField(db_index=True, default='created', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(db_index=True, default='Received', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_status',
            field=models.CharField(db_index=True, default='NOT_STARTED', max_length=50),
        ),
    ]
