# Generated by Django 6.0.6 on 2026-07-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0016_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpreference',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='approved_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='reference_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='source',
            field=models.CharField(choices=[('BOUTIQUE_CATALOG', 'Boutique Catalog'), ('CUSTOM_DESIGN', 'Custom Design'), ('PREVIOUS_DESIGN', 'Previous Design'), ('PINTEREST', 'Pinterest Inspiration'), ('GOOGLE', 'Google Images'), ('CUSTOMER_SKETCH', 'Customer Sketch'), ('DESIGNER_SKETCH', 'Designer Sketch')], db_index=True, default='BOUTIQUE_CATALOG', max_length=50),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to='crm_api.tailor'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='role',
            field=models.CharField(choices=[('Master', 'Master (generalist)'), ('Tailor', 'Tailor'), ('Measurement Master', 'Measurement Master'), ('Pattern Master', 'Pattern Master'), ('Cutting Master', 'Cutting Master'), ('Maggam Master', 'Maggam Master'), ('Finishing Master', 'Finishing Master'), ('Pressing Staff', 'Pressing Staff'), ('QC Master', 'QC Master')], default='Tailor', max_length=50),
        ),
    ]
