# Generated by Django 6.0.6 on 2026-08-12 11:02

import crm_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0024_normalise_customer_mobile_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiquesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=crm_api.models.upload_to_fabrics),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=crm_api.models.upload_to_customer_profiles),
        ),
        migrations.AlterField(
            model_name='garmentimage',
            name='image',
            field=models.ImageField(upload_to=crm_api.models.upload_to_finished_garments),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_garment_image',
            field=models.ImageField(blank=True, null=True, upload_to=crm_api.models.upload_to_completed_garments),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=crm_api.models.upload_to_stage_images),
        ),
    ]
