# Generated by Django 6.0.6 on 2026-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0029_alter_boutiquesettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquefabric',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='boutiquefabric',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
