# Generated by Django 6.0.6 on 2026-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0029_alter_boutiquesettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='invoice_template',
            field=models.CharField(blank=True, default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_template',
            field=models.CharField(blank=True, default='classic', max_length=50, null=True),
        ),
    ]
