# Generated by Django 6.0.6 on 2026-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0030_boutiquefabric_color_hex_boutiquefabric_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='role_modules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
