# Generated by Django 6.0.6 on 2026-09-08 09:17

import crm_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0032_finalise_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=crm_api.models.upload_to_staff_photos),
        ),
    ]
