# Generated by Django 6.0.6 on 2026-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0034_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='role',
            field=models.CharField(choices=[('Master', 'Master (generalist)'), ('Tailor', 'Tailor'), ('Maggam Master', 'Maggam Master'), ('Karigar', 'Karigar'), ('Packaging Staff', 'Packaging Staff'), ('QC Staff', 'QC Staff')], default='Tailor', max_length=50),
        ),
    ]
