# Generated by Django 6.0.6 on 2026-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0030_boutiquesettings_invoice_template_and_more'),
        ('crm_api', '0037_order_order_number'),
    ]

    operations = [
    ]
