# Generated by Django 6.0.6 on 2026-09-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0038_merge_20260910_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquefabric',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='boutiquefabric',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='FabricPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment', models.CharField(max_length=40)),
                ('section', models.CharField(blank=True, default='', max_length=60)),
                ('slot', models.CharField(blank=True, default='', max_length=60)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='crm_api.boutiquefabric')),
            ],
            options={
                'ordering': ['garment', 'section', 'slot'],
                'indexes': [models.Index(fields=['garment', 'section', 'slot'], name='crm_api_fab_garment_f610ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('fabric', 'garment', 'section', 'slot'), name='uniq_fabric_placement')],
            },
        ),
    ]
