# Generated by Django 6.0.6 on 2026-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0039_boutiquefabric_kind_boutiquefabric_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricplacement',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
