# Generated by Django 6.0.6 on 2026-09-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0040_fabricplacement_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(db_index=True, default='Silver', max_length=50),
        ),
    ]
