# Generated by Django 6.0.6 on 2026-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0041_customer_gender_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
