# Generated by Django 6.0.6 on 2026-09-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0042_orderstage_verification_note'),
        # The copy into inventory must land before the source tables go.
        ('inventory', '0012_fabric_catalogue_into_inventory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fabricplacement',
            name='crm_api_fab_garment_f610ff_idx',
        ),
        migrations.RemoveConstraint(
            model_name='fabricplacement',
            name='uniq_fabric_placement',
        ),
        migrations.RemoveField(
            model_name='fabricplacement',
            name='fabric',
        ),
        migrations.DeleteModel(
            name='BoutiqueFabric',
        ),
        migrations.DeleteModel(
            name='FabricPlacement',
        ),
    ]
