# Generated by Django 6.0.6 on 2026-07-24 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_api', '0016_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=50)),
                ('sequence', models.IntegerField(default=0)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=24.0, max_digits=5)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_images', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='crm_api.tailor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='crm_api.order')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REWORK_REQUIRED', 'Rework Required')], default='PASSED', max_length=50)),
                ('checklist_results', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True, null=True)),
                ('proof_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_qcs', to='crm_api.tailor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='crm_api.order')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_records', to='production.productiontask')),
            ],
        ),
    ]
