"""Routes for the platform console, mounted at /api/superadmin/.

The prefix is load-bearing rather than cosmetic: TenantHeaderMiddleware matches
on it (SUPERADMIN_PREFIX in tenants/middleware.py) to pin the connection to the
public schema before any of these views run. Moving the mount point in
boutique_crm/urls.py means moving that constant to match, or the console starts
resolving a tenant and reading the wrong schema's User table.
"""

from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .api_views import (AuditView, BoutiqueModulesView, ConfigView, ErrorDetailView,
                        ErrorsView, ErrorSummaryView, FlagDetailView, FlagsView,
                        HealthView, ModulesView, OnboardingView, OrdersMonitorView,
                        SearchView, SupportView, UserActionView, UsersView)
from .views import (BoutiqueDataView, LeadViewSet, OverviewView,
                    PlatformLoginView, PlatformLogoutView, PlatformMeView,
                    TenantViewSet)

# SimpleRouter, not DefaultRouter, and this is a security fix rather than a
# preference.
#
# DefaultRouter publishes an APIRootView at the router's mount point, and that
# view is generated by DRF -- so it takes settings.DEFAULT_PERMISSION_CLASSES,
# which is core.permissions.RolePermission. RolePermission asks
# core.roles.resolve_user_role, and on the public schema an ordinary
# authenticated account matches no profile and no tenant owner_email, so it
# falls through to the "nothing claimed this account" default and is answered
# OWNER. The console's own root was therefore readable by any signed-in user.
#
# Found by superadmin/test_api_security.py, which walks the URLconf and asserts
# every route declares IsPlatformAdmin -- exactly the class of route a
# hand-written list of endpoints would never have contained, because nobody
# wrote it.
#
# SimpleRouter generates no root view, which removes the view rather than
# guarding it. The console has no use for a browsable index.
router = SimpleRouter()
router.register(r'leads', LeadViewSet, basename='superadmin-lead')

urlpatterns = [
    path('auth/login/', PlatformLoginView.as_view(), name='superadmin-login'),
    path('auth/logout/', PlatformLogoutView.as_view(), name='superadmin-logout'),
    path('auth/me/', PlatformMeView.as_view(), name='superadmin-me'),

    path('overview/', OverviewView.as_view(), name='superadmin-overview'),

    path('boutiques/', TenantViewSet.as_view({'get': 'list'}),
         name='superadmin-boutiques'),
    path('boutiques/<str:schema_name>/', TenantViewSet.as_view({'get': 'retrieve'}),
         name='superadmin-boutique'),
    # POST, not PATCH on the boutique: these are the two things the console
    # *does*, and naming them keeps `is_active` off a general-purpose update
    # route where a stray payload could flip it.
    path('boutiques/<str:schema_name>/suspend/',
         TenantViewSet.as_view({'post': 'suspend'}), name='superadmin-suspend'),
    path('boutiques/<str:schema_name>/reactivate/',
         TenantViewSet.as_view({'post': 'reactivate'}), name='superadmin-reactivate'),

    # Everything inside a boutique. The <key> is 'app_label.model_name' and is
    # resolved against the browsable list rather than against Django's registry,
    # so naming an excluded model here reaches nothing -- see datasets.get_model.
    path('boutiques/<str:schema_name>/data/',
         BoutiqueDataView.as_view(), name='superadmin-data'),
    path('boutiques/<str:schema_name>/data/<str:key>/',
         BoutiqueDataView.as_view(), name='superadmin-dataset'),

    # --- The Control Center ---------------------------------------------
    #
    # Ordering matters where a literal segment could be read as a parameter.
    # 'boutiques/<schema_name>/' above is declared before these, and Django
    # matches in order, so any new 'boutiques/<something-literal>/' route must
    # go ABOVE it or the detail view will swallow it. The per-boutique routes
    # here all carry a further segment, so none of them collide.

    path('users/', UsersView.as_view(), name='superadmin-users'),
    path('users/<str:schema_name>/<str:username>/<str:action>/',
         UserActionView.as_view(), name='superadmin-user-action'),

    path('onboarding/', OnboardingView.as_view(), name='superadmin-onboarding'),
    path('onboarding/<str:schema_name>/', OnboardingView.as_view(),
         name='superadmin-onboarding-detail'),

    path('modules/', ModulesView.as_view(), name='superadmin-modules'),
    path('boutiques/<str:schema_name>/modules/', BoutiqueModulesView.as_view(),
         name='superadmin-boutique-modules'),

    path('flags/', FlagsView.as_view(), name='superadmin-flags'),
    path('flags/<str:key>/', FlagDetailView.as_view(), name='superadmin-flag'),

    path('config/', ConfigView.as_view(), name='superadmin-config'),
    path('health/', HealthView.as_view(), name='superadmin-health'),

    path('errors/', ErrorsView.as_view(), name='superadmin-errors'),
    path('errors/summary/', ErrorSummaryView.as_view(), name='superadmin-error-summary'),
    path('errors/<int:pk>/', ErrorDetailView.as_view(), name='superadmin-error'),

    path('audit/', AuditView.as_view(), name='superadmin-audit'),

    path('orders/', OrdersMonitorView.as_view(), name='superadmin-orders'),
    path('orders/<str:schema_name>/', OrdersMonitorView.as_view(),
         name='superadmin-orders-boutique'),

    path('search/', SearchView.as_view(), name='superadmin-search'),
    path('support/<str:schema_name>/', SupportView.as_view(), name='superadmin-support'),

    path('', include(router.urls)),
]
