# Generated by Django 6.0.6 on 2026-09-08 07:56

import apps.finance.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('MARKETING', 'Marketing'), ('MAINTENANCE', 'Maintenance & repairs'), ('SUPPLIES', 'Shop supplies'), ('PROFESSIONAL', 'Professional fees'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('incurred_on', models.DateField(db_index=True)),
                ('paid_to', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('receipt', models.FileField(blank=True, max_length=500, null=True, storage=apps.finance.models._receipt_storage, upload_to=apps.finance.models.upload_to_receipts)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
                'indexes': [models.Index(fields=['incurred_on', 'category'], name='finance_exp_incurre_4c99f2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='finance_expense_amount_not_negative')],
            },
        ),
    ]
