# Generated by Django 6.0.6 on 2026-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_boutiquetenant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquetenant',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=dict, help_text='Module switches this boutique has had changed, as {module_key: true/false}. A module that is not listed is on.'),
        ),
    ]
