# Generated by Django 6.0.6 on 2026-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_boutiquetenant_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquetenant',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA name, e.g. Asia/Kolkata. Used to show this boutique and its customers their own local time. Storage stays UTC.', max_length=64),
        ),
    ]
