# Generated by Django 6.0.6 on 2026-09-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_boutiquetenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier for the WhatsApp Baileys socket instance.', max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Paired WhatsApp phone number for this tenant.', max_length=32)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected')], default='DISCONNECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='tenants.boutiquetenant')),
            ],
        ),
    ]
