
CATALOG = [
    {
        'doc': 'MAGGAM',
        'sequence': 1,
        'section': 'Base Fabrics',
        'subsection': None,
        'items': [
            ('Raw Silk', 'MATERIAL', 'METER'),
            ('Pure Silk', 'MATERIAL', 'METER'),
            ('Dupion Silk', 'MATERIAL', 'METER'),
            ('Tussar Silk', 'MATERIAL', 'METER'),
            ('Kanchipuram Silk', 'MATERIAL', 'METER'),
            ('Banarasi Silk', 'MATERIAL', 'METER'),
            ('Velvet', 'MATERIAL', 'METER'),
            ('Cotton', 'MATERIAL', 'METER'),
            ('Linen', 'MATERIAL', 'METER'),
            ('Chanderi', 'MATERIAL', 'METER'),
            ('Tissue', 'MATERIAL', 'METER'),
            ('Organza', 'MATERIAL', 'METER'),
            ('Georgette', 'MATERIAL', 'METER'),
            ('Crepe', 'MATERIAL', 'METER'),
            ('Satin', 'MATERIAL', 'METER'),
            ('Net', 'MATERIAL', 'METER'),
            ('French Net', 'MATERIAL', 'METER'),
            ('Tulle', 'MATERIAL', 'METER'),
            ('Mesh', 'MATERIAL', 'METER'),
            ('Lycra', 'MATERIAL', 'METER'),
            ('Brocade', 'MATERIAL', 'METER'),
            ('Jacquard', 'MATERIAL', 'METER'),
            ('Muslin', 'MATERIAL', 'METER'),
            ('Modal', 'MATERIAL', 'METER'),
            ('Rayon', 'MATERIAL', 'METER'),
            ('Khadi', 'MATERIAL', 'METER'),
            ('Denim', 'MATERIAL', 'METER'),
            ('Canvas', 'MATERIAL', 'METER'),
            ('Leather (fashion embroidery)', 'MATERIAL', 'METER'),
            ('Faux Leather', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 2,
        'section': 'Embroidery Threads',
        'subsection': None,
        'items': [
            ('Cotton Thread', 'MATERIAL', 'PIECE'),
            ('Silk Thread', 'MATERIAL', 'PIECE'),
            ('Rayon Thread', 'MATERIAL', 'PIECE'),
            ('Polyester Thread', 'MATERIAL', 'PIECE'),
            ('Viscose Thread', 'MATERIAL', 'PIECE'),
            ('Metallic Thread', 'MATERIAL', 'PIECE'),
            ('Nylon Thread', 'MATERIAL', 'PIECE'),
            ('Wool Thread', 'MATERIAL', 'PIECE'),
            ('Anchor Thread', 'MATERIAL', 'PIECE'),
            ('DMC Thread', 'MATERIAL', 'PIECE'),
            ('Resham Thread', 'MATERIAL', 'PIECE'),
            ('Artificial Silk Thread', 'MATERIAL', 'PIECE'),
            ('Twisted Silk Thread', 'MATERIAL', 'PIECE'),
            ('Multi-color Thread', 'MATERIAL', 'PIECE'),
            ('Ombre Thread', 'MATERIAL', 'PIECE'),
            ('Matte Thread', 'MATERIAL', 'PIECE'),
            ('Glossy Thread', 'MATERIAL', 'PIECE'),
            ('Invisible Thread', 'MATERIAL', 'PIECE'),
            ('Elastic Thread', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 2,
        'section': 'Embroidery Threads',
        'subsection': 'Metallic Threads',
        'items': [
            ('Zari Gold', 'MATERIAL', 'PIECE'),
            ('Silver Zari', 'MATERIAL', 'PIECE'),
            ('Copper Zari', 'MATERIAL', 'PIECE'),
            ('Antique Gold', 'MATERIAL', 'PIECE'),
            ('Antique Silver', 'MATERIAL', 'PIECE'),
            ('Metallic Wire Thread', 'MATERIAL', 'PIECE'),
            ('Kasab', 'MATERIAL', 'PIECE'),
            ('Badla', 'MATERIAL', 'PIECE'),
            ('Tested Zari', 'MATERIAL', 'PIECE'),
            ('Pure Silver Zari', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 3,
        'section': 'Needles',
        'subsection': None,
        'items': [
            ('Aari Needle', 'TOOL', 'PIECE'),
            ('Maggam Needle', 'TOOL', 'PIECE'),
            ('Zardosi Needle', 'TOOL', 'PIECE'),
            ('Crewel Needle', 'TOOL', 'PIECE'),
            ('Chenille Needle', 'TOOL', 'PIECE'),
            ('Beading Needle', 'TOOL', 'PIECE'),
            ('Tapestry Needle', 'TOOL', 'PIECE'),
            ('Sharps', 'TOOL', 'PIECE'),
            ('Milliner Needle', 'TOOL', 'PIECE'),
            ('Straw Needle', 'TOOL', 'PIECE'),
            ('Bullion Needle', 'TOOL', 'PIECE'),
            ('Curved Needle', 'TOOL', 'PIECE'),
            ('Leather Needle', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 4,
        'section': 'Frames',
        'subsection': None,
        'items': [
            ('Maggam Frame', 'TOOL', 'PIECE'),
            ('Adda Frame', 'TOOL', 'PIECE'),
            ('Wooden Hoop', 'TOOL', 'PIECE'),
            ('Plastic Hoop', 'TOOL', 'PIECE'),
            ('Adjustable Stand', 'TOOL', 'PIECE'),
            ('Floor Stand', 'TOOL', 'PIECE'),
            ('Clamp Frame', 'TOOL', 'PIECE'),
            ('Rotating Frame', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Glass Beads',
        'items': [
            ('Seed Beads', 'MATERIAL', 'PIECE'),
            ('Czech Beads', 'MATERIAL', 'PIECE'),
            ('Japanese Miyuki Beads', 'MATERIAL', 'PIECE'),
            ('Toho Beads', 'MATERIAL', 'PIECE'),
            ('Bugle Beads', 'MATERIAL', 'PIECE'),
            ('Tube Beads', 'MATERIAL', 'PIECE'),
            ('Cut Beads', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Plastic Beads',
        'items': [
            ('Pony Beads', 'MATERIAL', 'PIECE'),
            ('Acrylic Beads', 'MATERIAL', 'PIECE'),
            ('Resin Beads', 'MATERIAL', 'PIECE'),
            ('ABS Beads', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Crystal Beads',
        'items': [
            ('Swarovski', 'MATERIAL', 'PIECE'),
            ('Preciosa', 'MATERIAL', 'PIECE'),
            ('Chinese Crystal', 'MATERIAL', 'PIECE'),
            ('Bicone', 'MATERIAL', 'PIECE'),
            ('Rondelle', 'MATERIAL', 'PIECE'),
            ('Cube Crystal', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Stone Beads',
        'items': [
            ('Agate', 'MATERIAL', 'PIECE'),
            ('Jade', 'MATERIAL', 'PIECE'),
            ('Quartz', 'MATERIAL', 'PIECE'),
            ('Onyx', 'MATERIAL', 'PIECE'),
            ('Aventurine', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Metal Beads',
        'items': [
            ('Gold Beads', 'MATERIAL', 'PIECE'),
            ('Silver Beads', 'MATERIAL', 'PIECE'),
            ('Copper Beads', 'MATERIAL', 'PIECE'),
            ('Brass Beads', 'MATERIAL', 'PIECE'),
            ('Antique Finish', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Other Beads',
        'items': [
            ('Wooden Beads', 'MATERIAL', 'PIECE'),
            ('Ceramic Beads', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 5,
        'section': 'Beads',
        'subsection': 'Pearl Beads',
        'items': [
            ('Half Pearls', 'MATERIAL', 'PIECE'),
            ('Full Pearls', 'MATERIAL', 'PIECE'),
            ('Rice Pearls', 'MATERIAL', 'PIECE'),
            ('Baroque Pearls', 'MATERIAL', 'PIECE'),
            ('Shell Pearls', 'MATERIAL', 'PIECE'),
            ('Freshwater Pearls', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 6,
        'section': 'Stones',
        'subsection': None,
        'items': [
            ('Kundan Stones', 'MATERIAL', 'PIECE'),
            ('American Diamond', 'MATERIAL', 'PIECE'),
            ('Rhinestones', 'MATERIAL', 'PIECE'),
            ('Chatons', 'MATERIAL', 'PIECE'),
            ('Flatback Stones', 'MATERIAL', 'PIECE'),
            ('Hotfix Stones', 'MATERIAL', 'PIECE'),
            ('Non-hotfix Stones', 'MATERIAL', 'PIECE'),
            ('Crystal Stones', 'MATERIAL', 'PIECE'),
            ('Resin Stones', 'MATERIAL', 'PIECE'),
            ('Acrylic Stones', 'MATERIAL', 'PIECE'),
            ('Glass Stones', 'MATERIAL', 'PIECE'),
            ('Cabochons', 'MATERIAL', 'PIECE'),
            ('Dome Stones', 'MATERIAL', 'PIECE'),
            ('Oval Stones', 'MATERIAL', 'PIECE'),
            ('Navette Stones', 'MATERIAL', 'PIECE'),
            ('Pear Shape', 'MATERIAL', 'PIECE'),
            ('Marquise', 'MATERIAL', 'PIECE'),
            ('Square', 'MATERIAL', 'PIECE'),
            ('Rectangle', 'MATERIAL', 'PIECE'),
            ('Triangle', 'MATERIAL', 'PIECE'),
            ('Teardrop', 'MATERIAL', 'PIECE'),
            ('Emerald Cut', 'MATERIAL', 'PIECE'),
            ('Cushion Cut', 'MATERIAL', 'PIECE'),
            ('Octagon', 'MATERIAL', 'PIECE'),
            ('Round', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 7,
        'section': 'Sequins',
        'subsection': None,
        'items': [
            ('Flat Sequins', 'MATERIAL', 'PIECE'),
            ('Cup Sequins', 'MATERIAL', 'PIECE'),
            ('Flower Sequins', 'MATERIAL', 'PIECE'),
            ('Leaf Sequins', 'MATERIAL', 'PIECE'),
            ('Holographic Sequins', 'MATERIAL', 'PIECE'),
            ('Matte Sequins', 'MATERIAL', 'PIECE'),
            ('Transparent Sequins', 'MATERIAL', 'PIECE'),
            ('Metallic Sequins', 'MATERIAL', 'PIECE'),
            ('Pearl Sequins', 'MATERIAL', 'PIECE'),
            ('Laser Sequins', 'MATERIAL', 'PIECE'),
            ('PVC Sequins', 'MATERIAL', 'PIECE'),
            ('PET Sequins', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 8,
        'section': 'Mirrors',
        'subsection': None,
        'items': [
            ('Round Mirrors', 'MATERIAL', 'PIECE'),
            ('Square Mirrors', 'MATERIAL', 'PIECE'),
            ('Triangle Mirrors', 'MATERIAL', 'PIECE'),
            ('Oval Mirrors', 'MATERIAL', 'PIECE'),
            ('Acrylic Mirrors', 'MATERIAL', 'PIECE'),
            ('Glass Mirrors', 'MATERIAL', 'PIECE'),
            ('Laser Cut Mirrors', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 9,
        'section': 'Traditional Zardosi Materials',
        'subsection': None,
        'items': [
            ('Dabka', 'MATERIAL', 'PIECE'),
            ('Nakshi', 'MATERIAL', 'PIECE'),
            ('Kasab', 'MATERIAL', 'PIECE'),
            ('Salma', 'MATERIAL', 'PIECE'),
            ('Sitara', 'MATERIAL', 'PIECE'),
            ('Kora', 'MATERIAL', 'PIECE'),
            ('Katori', 'MATERIAL', 'PIECE'),
            ('Gijai', 'MATERIAL', 'PIECE'),
            ('Gota Patti', 'MATERIAL', 'PIECE'),
            ('Tilla', 'MATERIAL', 'PIECE'),
            ('Badla', 'MATERIAL', 'PIECE'),
            ('Kundan', 'MATERIAL', 'PIECE'),
            ('Moti', 'MATERIAL', 'PIECE'),
            ('Marori Wire', 'MATERIAL', 'PIECE'),
            ('French Wire', 'MATERIAL', 'PIECE'),
            ('Purl Wire', 'MATERIAL', 'PIECE'),
            ('Bullion Wire', 'MATERIAL', 'PIECE'),
            ('Coils', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 10,
        'section': 'Laces & Borders',
        'subsection': None,
        'items': [
            ('Zari Lace', 'MATERIAL', 'METER'),
            ('Cotton Lace', 'MATERIAL', 'METER'),
            ('Crochet Lace', 'MATERIAL', 'METER'),
            ('Organza Lace', 'MATERIAL', 'METER'),
            ('Velvet Lace', 'MATERIAL', 'METER'),
            ('Pearl Lace', 'MATERIAL', 'METER'),
            ('Stone Lace', 'MATERIAL', 'METER'),
            ('Mirror Lace', 'MATERIAL', 'METER'),
            ('Sequin Lace', 'MATERIAL', 'METER'),
            ('Beaded Lace', 'MATERIAL', 'METER'),
            ('Fringes', 'MATERIAL', 'METER'),
            ('Tassel Lace', 'MATERIAL', 'METER'),
            ('Pom Pom Lace', 'MATERIAL', 'METER'),
            ('Scallop Lace', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 11,
        'section': 'Appliqué Materials',
        'subsection': None,
        'items': [
            ('Felt', 'MATERIAL', 'PIECE'),
            ('Velvet Patch', 'MATERIAL', 'PIECE'),
            ('Organza Patch', 'MATERIAL', 'PIECE'),
            ('Leather Patch', 'MATERIAL', 'PIECE'),
            ('Net Patch', 'MATERIAL', 'PIECE'),
            ('Printed Patch', 'MATERIAL', 'PIECE'),
            ('Embroidered Patch', 'MATERIAL', 'PIECE'),
            ('Mirror Patch', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 12,
        'section': 'Cords & Decorative Elements',
        'subsection': None,
        'items': [
            ('Silk Cord', 'MATERIAL', 'PIECE'),
            ('Twisted Cord', 'MATERIAL', 'PIECE'),
            ('Cotton Cord', 'MATERIAL', 'PIECE'),
            ('Metallic Cord', 'MATERIAL', 'PIECE'),
            ('Braided Cord', 'MATERIAL', 'PIECE'),
            ('Soutache Cord', 'MATERIAL', 'PIECE'),
            ('Rope', 'MATERIAL', 'PIECE'),
            ('Tassels', 'MATERIAL', 'PIECE'),
            ('Latkans', 'MATERIAL', 'PIECE'),
            ('Pom Poms', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 13,
        'section': 'Backing & Support Materials',
        'subsection': None,
        'items': [
            ('Buckram', 'MATERIAL', 'PIECE'),
            ('Interlining', 'MATERIAL', 'PIECE'),
            ('Canvas', 'MATERIAL', 'PIECE'),
            ('Fusing', 'MATERIAL', 'PIECE'),
            ('Pellon', 'MATERIAL', 'PIECE'),
            ('Cotton Backing', 'MATERIAL', 'PIECE'),
            ('Stiffener', 'MATERIAL', 'PIECE'),
            ('Foam Sheet', 'MATERIAL', 'PIECE'),
            ('Felt Sheet', 'MATERIAL', 'PIECE'),
            ('Muslin', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 14,
        'section': 'Adhesives',
        'subsection': None,
        'items': [
            ('Fabric Glue', 'CONSUMABLE', 'PIECE'),
            ('Fevicol MR', 'CONSUMABLE', 'PIECE'),
            ('Silicone Glue', 'CONSUMABLE', 'PIECE'),
            ('Hot Glue', 'CONSUMABLE', 'PIECE'),
            ('Fabric Adhesive Spray', 'CONSUMABLE', 'PIECE'),
            ('Stone Glue', 'CONSUMABLE', 'PIECE'),
            ('Textile Adhesive', 'CONSUMABLE', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 15,
        'section': 'Marking Tools',
        'subsection': None,
        'items': [
            ('Tailor Chalk', 'TOOL', 'PIECE'),
            ('Chalk Pencil', 'TOOL', 'PIECE'),
            ('Carbon Paper', 'TOOL', 'PIECE'),
            ('Tracing Paper', 'TOOL', 'PIECE'),
            ('Butter Paper', 'TOOL', 'PIECE'),
            ('Heat Erasable Pen', 'TOOL', 'PIECE'),
            ('Water Soluble Pen', 'TOOL', 'PIECE'),
            ('Fabric Marker', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 16,
        'section': 'Cutting Tools',
        'subsection': None,
        'items': [
            ('Embroidery Scissors', 'TOOL', 'PIECE'),
            ('Thread Cutter', 'TOOL', 'PIECE'),
            ('Snips', 'TOOL', 'PIECE'),
            ('Rotary Cutter', 'TOOL', 'PIECE'),
            ('Fabric Scissors', 'TOOL', 'PIECE'),
            ('Precision Knife', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 17,
        'section': 'Measuring Tools',
        'subsection': None,
        'items': [
            ('Measuring Tape', 'TOOL', 'PIECE'),
            ('Scale', 'TOOL', 'PIECE'),
            ('French Curve', 'TOOL', 'PIECE'),
            ('Pattern Master', 'TOOL', 'PIECE'),
            ('Compass', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 18,
        'section': 'Finishing Materials',
        'subsection': None,
        'items': [
            ('Steam Press Cloth', 'TOOL', 'PIECE'),
            ('Pressing Mat', 'TOOL', 'PIECE'),
            ('Iron', 'TOOL', 'PIECE'),
            ('Steam Iron', 'TOOL', 'PIECE'),
            ('Lint Roller', 'TOOL', 'PIECE'),
            ('Fabric Protector', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 19,
        'section': 'Decorative Embellishments',
        'subsection': None,
        'items': [
            ('Feathers', 'MATERIAL', 'PIECE'),
            ('Ostrich Feathers', 'MATERIAL', 'PIECE'),
            ('Fur Trim', 'MATERIAL', 'PIECE'),
            ('Silk Flowers', 'MATERIAL', 'PIECE'),
            ('Fabric Flowers', 'MATERIAL', 'PIECE'),
            ('Metal Charms', 'MATERIAL', 'PIECE'),
            ('Coins', 'MATERIAL', 'PIECE'),
            ('Bells', 'MATERIAL', 'PIECE'),
            ('Shells', 'MATERIAL', 'PIECE'),
            ('Cowrie Shells', 'MATERIAL', 'PIECE'),
            ('Wooden Shapes', 'MATERIAL', 'PIECE'),
            ('Resin Motifs', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 20,
        'section': 'Modern Luxury Embellishments',
        'subsection': None,
        'items': [
            ('Swarovski Crystals', 'MATERIAL', 'PIECE'),
            ('Austrian Crystals', 'MATERIAL', 'PIECE'),
            ('Cubic Zirconia Elements', 'MATERIAL', 'PIECE'),
            ('Crystal Chains', 'MATERIAL', 'PIECE'),
            ('Rhinestone Chains', 'MATERIAL', 'PIECE'),
            ('Pearl Chains', 'MATERIAL', 'PIECE'),
            ('Diamond Mesh', 'MATERIAL', 'PIECE'),
            ('Metal Mesh', 'MATERIAL', 'PIECE'),
            ('Studs', 'MATERIAL', 'PIECE'),
            ('Spikes', 'MATERIAL', 'PIECE'),
            ('Rivets', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 21,
        'section': 'Specialty Materials',
        'subsection': None,
        'items': [
            ('Glow-in-the-dark Beads', 'MATERIAL', 'PIECE'),
            ('UV Color-changing Beads', 'MATERIAL', 'PIECE'),
            ('Reflective Beads', 'MATERIAL', 'PIECE'),
            ('Magnetic Clasps', 'MATERIAL', 'PIECE'),
            ('3D Printed Embellishments', 'MATERIAL', 'PIECE'),
            ('Laser-cut Acrylic Shapes', 'MATERIAL', 'PIECE'),
            ('Laser-cut MDF Motifs', 'MATERIAL', 'PIECE'),
            ('Resin Art Pieces', 'MATERIAL', 'PIECE'),
            ('Polymer Clay Embellishments', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'MAGGAM',
        'sequence': 22,
        'section': 'Tools & Accessories',
        'subsection': None,
        'items': [
            ('Thread Wax', 'TOOL', 'PIECE'),
            ('Beeswax', 'TOOL', 'PIECE'),
            ('Needle Threader', 'TOOL', 'PIECE'),
            ('Bobbins', 'TOOL', 'PIECE'),
            ('Thread Organizer', 'TOOL', 'PIECE'),
            ('Bead Organizer', 'TOOL', 'PIECE'),
            ('Storage Boxes', 'TOOL', 'PIECE'),
            ('Tweezers', 'TOOL', 'PIECE'),
            ('Magnifying Lamp', 'TOOL', 'PIECE'),
            ('Finger Protectors', 'TOOL', 'PIECE'),
            ('Needle Cushion', 'TOOL', 'PIECE'),
            ('Pin Cushion', 'TOOL', 'PIECE'),
            ('Safety Pins', 'TOOL', 'PIECE'),
            ('Dressmaker Pins', 'TOOL', 'PIECE'),
            ('Clips', 'TOOL', 'PIECE'),
            ('Fabric Clips', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 1,
        'section': 'Product Planning & Design',
        'subsection': None,
        'items': [
            ('Fashion trend books', 'ASSET', 'UNIT'),
            ('Pantone color guides', 'ASSET', 'UNIT'),
            ('Mood boards', 'ASSET', 'UNIT'),
            ('Fabric swatches', 'ASSET', 'UNIT'),
            ('Trim library', 'ASSET', 'UNIT'),
            ('Sample garments', 'ASSET', 'UNIT'),
            ('Fashion sketches', 'ASSET', 'UNIT'),
            ('Technical drawings', 'ASSET', 'UNIT'),
            ('Tech packs', 'ASSET', 'UNIT'),
            ('Measurement charts', 'ASSET', 'UNIT'),
            ('Size charts', 'ASSET', 'UNIT'),
            ('Grading sheets', 'ASSET', 'UNIT'),
            ('Pattern specifications', 'ASSET', 'UNIT'),
            ('Wash care standards', 'ASSET', 'UNIT'),
            ('Brand guidelines', 'ASSET', 'UNIT'),
            ('Collection boards', 'ASSET', 'UNIT'),
            ('CAD software', 'SYSTEM', 'UNIT'),
            ('Design tablets', 'ASSET', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Cotton',
        'items': [
            ('Poplin', 'MATERIAL', 'METER'),
            ('Cambric', 'MATERIAL', 'METER'),
            ('Voile', 'MATERIAL', 'METER'),
            ('Lawn', 'MATERIAL', 'METER'),
            ('Slub Cotton', 'MATERIAL', 'METER'),
            ('Cotton Satin', 'MATERIAL', 'METER'),
            ('Cotton Twill', 'MATERIAL', 'METER'),
            ('Oxford Cotton', 'MATERIAL', 'METER'),
            ('Brushed Cotton', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Linen',
        'items': [
            ('Pure Linen', 'MATERIAL', 'METER'),
            ('Linen Blend', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Silk',
        'items': [
            ('Raw Silk', 'MATERIAL', 'METER'),
            ('Dupion', 'MATERIAL', 'METER'),
            ('Tussar', 'MATERIAL', 'METER'),
            ('Banarasi', 'MATERIAL', 'METER'),
            ('Chanderi', 'MATERIAL', 'METER'),
            ('Organza Silk', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Synthetic',
        'items': [
            ('Polyester', 'MATERIAL', 'METER'),
            ('Rayon', 'MATERIAL', 'METER'),
            ('Viscose', 'MATERIAL', 'METER'),
            ('Modal', 'MATERIAL', 'METER'),
            ('Nylon', 'MATERIAL', 'METER'),
            ('Acrylic', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Knits',
        'items': [
            ('Jersey', 'MATERIAL', 'METER'),
            ('Rib Knit', 'MATERIAL', 'METER'),
            ('Ponte', 'MATERIAL', 'METER'),
            ('Interlock', 'MATERIAL', 'METER'),
            ('French Terry', 'MATERIAL', 'METER'),
            ('Fleece', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 2,
        'section': 'Fabrics',
        'subsection': 'Luxury',
        'items': [
            ('Velvet', 'MATERIAL', 'METER'),
            ('Brocade', 'MATERIAL', 'METER'),
            ('Jacquard', 'MATERIAL', 'METER'),
            ('Satin', 'MATERIAL', 'METER'),
            ('Crepe', 'MATERIAL', 'METER'),
            ('Georgette', 'MATERIAL', 'METER'),
            ('Chiffon', 'MATERIAL', 'METER'),
            ('Net', 'MATERIAL', 'METER'),
            ('Tulle', 'MATERIAL', 'METER'),
            ('Mesh', 'MATERIAL', 'METER'),
            ('Lace', 'MATERIAL', 'METER'),
            ('Sequin Fabric', 'MATERIAL', 'METER'),
            ('Tissue', 'MATERIAL', 'METER'),
            ('Lurex', 'MATERIAL', 'METER'),
            ('Denim', 'MATERIAL', 'METER'),
            ('Corduroy', 'MATERIAL', 'METER'),
            ('Canvas', 'MATERIAL', 'METER'),
            ('Leather', 'MATERIAL', 'METER'),
            ('Faux Leather', 'MATERIAL', 'METER'),
            ('Suede', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 3,
        'section': 'Interlining & Support',
        'subsection': None,
        'items': [
            ('Fusible Interlining', 'MATERIAL', 'METER'),
            ('Non-fusible Interlining', 'MATERIAL', 'METER'),
            ('Buckram', 'MATERIAL', 'METER'),
            ('Collar Fusing', 'MATERIAL', 'METER'),
            ('Cuff Fusing', 'MATERIAL', 'METER'),
            ('Waistband Fusing', 'MATERIAL', 'METER'),
            ('Shoulder Pads', 'MATERIAL', 'METER'),
            ('Sleeve Heads', 'MATERIAL', 'METER'),
            ('Canvas', 'MATERIAL', 'METER'),
            ('Hair Canvas', 'MATERIAL', 'METER'),
            ('Foam', 'MATERIAL', 'METER'),
            ('Wadding', 'MATERIAL', 'METER'),
            ('Quilt Batting', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 4,
        'section': 'Sewing Threads',
        'subsection': None,
        'items': [
            ('Cotton Thread', 'MATERIAL', 'PIECE'),
            ('Polyester Thread', 'MATERIAL', 'PIECE'),
            ('Nylon Thread', 'MATERIAL', 'PIECE'),
            ('Silk Thread', 'MATERIAL', 'PIECE'),
            ('Rayon Thread', 'MATERIAL', 'PIECE'),
            ('Metallic Thread', 'MATERIAL', 'PIECE'),
            ('Elastic Thread', 'MATERIAL', 'PIECE'),
            ('Invisible Thread', 'MATERIAL', 'PIECE'),
            ('Overlock Thread', 'MATERIAL', 'PIECE'),
            ('Embroidery Thread', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 5,
        'section': 'Buttons',
        'subsection': None,
        'items': [
            ('Plastic Buttons', 'MATERIAL', 'PIECE'),
            ('Polyester Buttons', 'MATERIAL', 'PIECE'),
            ('Wooden Buttons', 'MATERIAL', 'PIECE'),
            ('Coconut Buttons', 'MATERIAL', 'PIECE'),
            ('Horn Buttons', 'MATERIAL', 'PIECE'),
            ('Shell Buttons', 'MATERIAL', 'PIECE'),
            ('Metal Buttons', 'MATERIAL', 'PIECE'),
            ('Brass Buttons', 'MATERIAL', 'PIECE'),
            ('Snap Buttons', 'MATERIAL', 'PIECE'),
            ('Jeans Buttons', 'MATERIAL', 'PIECE'),
            ('Fabric Buttons', 'MATERIAL', 'PIECE'),
            ('Covered Buttons', 'MATERIAL', 'PIECE'),
            ('Crystal Buttons', 'MATERIAL', 'PIECE'),
            ('Pearl Buttons', 'MATERIAL', 'PIECE'),
            ('Decorative Buttons', 'MATERIAL', 'PIECE'),
            ('Toggle Buttons', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 6,
        'section': 'Zippers',
        'subsection': None,
        'items': [
            ('Nylon Zip', 'MATERIAL', 'PIECE'),
            ('Metal Zip', 'MATERIAL', 'PIECE'),
            ('Invisible Zip', 'MATERIAL', 'PIECE'),
            ('Concealed Zip', 'MATERIAL', 'PIECE'),
            ('Waterproof Zip', 'MATERIAL', 'PIECE'),
            ('Open-end Zip', 'MATERIAL', 'PIECE'),
            ('Closed-end Zip', 'MATERIAL', 'PIECE'),
            ('Two-way Zip', 'MATERIAL', 'PIECE'),
            ('Decorative Zip', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 7,
        'section': 'Elastics',
        'subsection': None,
        'items': [
            ('Waist Elastic', 'MATERIAL', 'METER'),
            ('Knitted Elastic', 'MATERIAL', 'METER'),
            ('Woven Elastic', 'MATERIAL', 'METER'),
            ('Transparent Elastic', 'MATERIAL', 'METER'),
            ('Fold-over Elastic', 'MATERIAL', 'METER'),
            ('Buttonhole Elastic', 'MATERIAL', 'METER'),
            ('Draw Cord Elastic', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 8,
        'section': 'Labels & Branding',
        'subsection': None,
        'items': [
            ('Main Brand Label', 'MATERIAL', 'PIECE'),
            ('Size Label', 'MATERIAL', 'PIECE'),
            ('Wash Care Label', 'MATERIAL', 'PIECE'),
            ('Composition Label', 'MATERIAL', 'PIECE'),
            ('Country of Origin Label', 'MATERIAL', 'PIECE'),
            ('Barcode Label', 'MATERIAL', 'PIECE'),
            ('Price Tag', 'MATERIAL', 'PIECE'),
            ('Hang Tag', 'MATERIAL', 'PIECE'),
            ('QR Code Tag', 'MATERIAL', 'PIECE'),
            ('RFID Tag', 'MATERIAL', 'PIECE'),
            ('Hologram Label', 'MATERIAL', 'PIECE'),
            ('Brand Sticker', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 9,
        'section': 'Decorative Materials',
        'subsection': None,
        'items': [
            ('Lace', 'MATERIAL', 'METER'),
            ('Frills', 'MATERIAL', 'METER'),
            ('Ruffles', 'MATERIAL', 'METER'),
            ('Tassels', 'MATERIAL', 'METER'),
            ('Pom Poms', 'MATERIAL', 'METER'),
            ('Gota Patti', 'MATERIAL', 'METER'),
            ('Piping', 'MATERIAL', 'METER'),
            ('Bias Tape', 'MATERIAL', 'METER'),
            ('Satin Ribbon', 'MATERIAL', 'METER'),
            ('Grosgrain Ribbon', 'MATERIAL', 'METER'),
            ('Velvet Ribbon', 'MATERIAL', 'METER'),
            ('Cotton Tape', 'MATERIAL', 'METER'),
            ('Decorative Tape', 'MATERIAL', 'METER'),
            ('Cord', 'MATERIAL', 'METER'),
            ('Braids', 'MATERIAL', 'METER'),
            ('Fringe', 'MATERIAL', 'METER'),
            ('Beads', 'MATERIAL', 'METER'),
            ('Stones', 'MATERIAL', 'METER'),
            ('Pearls', 'MATERIAL', 'METER'),
            ('Sequins', 'MATERIAL', 'METER'),
            ('Mirrors', 'MATERIAL', 'METER'),
            ('Embroidery Patches', 'MATERIAL', 'METER'),
            ('Printed Patches', 'MATERIAL', 'METER'),
            ('Appliqué', 'MATERIAL', 'METER'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 10,
        'section': 'Maggam / Hand Embroidery Materials',
        'subsection': None,
        'items': [
            ('Aari Needles', 'MATERIAL', 'PIECE'),
            ('Zardosi Needles', 'MATERIAL', 'PIECE'),
            ('Dabka', 'MATERIAL', 'PIECE'),
            ('Nakshi', 'MATERIAL', 'PIECE'),
            ('Kasab', 'MATERIAL', 'PIECE'),
            ('Salma', 'MATERIAL', 'PIECE'),
            ('Sitara', 'MATERIAL', 'PIECE'),
            ('Zari', 'MATERIAL', 'PIECE'),
            ('Resham Thread', 'MATERIAL', 'PIECE'),
            ('Seed Beads', 'MATERIAL', 'PIECE'),
            ('Bugle Beads', 'MATERIAL', 'PIECE'),
            ('Pearls', 'MATERIAL', 'PIECE'),
            ('Kundan', 'MATERIAL', 'PIECE'),
            ('Swarovski Crystals', 'MATERIAL', 'PIECE'),
            ('Rhinestones', 'MATERIAL', 'PIECE'),
            ('Mirrors', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 11,
        'section': 'Printing Materials',
        'subsection': None,
        'items': [
            ('Screen Printing Ink', 'CONSUMABLE', 'PIECE'),
            ('Pigment Ink', 'CONSUMABLE', 'PIECE'),
            ('Reactive Dye', 'CONSUMABLE', 'PIECE'),
            ('Sublimation Ink', 'CONSUMABLE', 'PIECE'),
            ('DTG Ink', 'CONSUMABLE', 'PIECE'),
            ('DTF Film', 'CONSUMABLE', 'PIECE'),
            ('Heat Transfer Vinyl', 'CONSUMABLE', 'PIECE'),
            ('Foil Sheets', 'CONSUMABLE', 'PIECE'),
            ('Puff Ink', 'CONSUMABLE', 'PIECE'),
            ('Metallic Ink', 'CONSUMABLE', 'PIECE'),
            ('Reflective Film', 'CONSUMABLE', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 12,
        'section': 'Garment Accessories',
        'subsection': None,
        'items': [
            ('Hooks', 'MATERIAL', 'PIECE'),
            ('Eyes', 'MATERIAL', 'PIECE'),
            ('Press Buttons', 'MATERIAL', 'PIECE'),
            ('Rivets', 'MATERIAL', 'PIECE'),
            ('Eyelets', 'MATERIAL', 'PIECE'),
            ('D Rings', 'MATERIAL', 'PIECE'),
            ('O Rings', 'MATERIAL', 'PIECE'),
            ('Buckles', 'MATERIAL', 'PIECE'),
            ('Belt Loops', 'MATERIAL', 'PIECE'),
            ('Velcro', 'MATERIAL', 'PIECE'),
            ('Cord Locks', 'MATERIAL', 'PIECE'),
            ('Toggle Stops', 'MATERIAL', 'PIECE'),
            ('Drawstrings', 'MATERIAL', 'PIECE'),
            ('Rope', 'MATERIAL', 'PIECE'),
            ('Elastic Cord', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 13,
        'section': 'Pattern Making Tools',
        'subsection': None,
        'items': [
            ('Pattern Paper', 'TOOL', 'PIECE'),
            ('Brown Paper', 'TOOL', 'PIECE'),
            ('Tracing Wheel', 'TOOL', 'PIECE'),
            ('Carbon Paper', 'TOOL', 'PIECE'),
            ('French Curve', 'TOOL', 'PIECE'),
            ('L Scale', 'TOOL', 'PIECE'),
            ('Hip Curve', 'TOOL', 'PIECE'),
            ('Measuring Tape', 'TOOL', 'PIECE'),
            ('Grading Ruler', 'TOOL', 'PIECE'),
            ('Notcher', 'TOOL', 'PIECE'),
            ('Awl', 'TOOL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 14,
        'section': 'Cutting Room',
        'subsection': None,
        'items': [
            ('Fabric Spreader', 'MACHINE', 'UNIT'),
            ('Cutting Table', 'ASSET', 'UNIT'),
            ('Fabric Weights', 'TOOL', 'PIECE'),
            ('Fabric Clips', 'TOOL', 'PIECE'),
            ('Rotary Cutter', 'TOOL', 'PIECE'),
            ('Straight Knife', 'MACHINE', 'UNIT'),
            ('Band Knife', 'MACHINE', 'UNIT'),
            ('Electric Cutter', 'MACHINE', 'UNIT'),
            ('Scissors', 'TOOL', 'PIECE'),
            ('Snips', 'TOOL', 'PIECE'),
            ('Marker Paper', 'CONSUMABLE', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 15,
        'section': 'Sewing Machines',
        'subsection': None,
        'items': [
            ('Single Needle Lockstitch', 'MACHINE', 'UNIT'),
            ('Double Needle', 'MACHINE', 'UNIT'),
            ('Overlock', 'MACHINE', 'UNIT'),
            ('Flatlock', 'MACHINE', 'UNIT'),
            ('Feed-off-the-arm', 'MACHINE', 'UNIT'),
            ('Cylinder Bed', 'MACHINE', 'UNIT'),
            ('Bartack Machine', 'MACHINE', 'UNIT'),
            ('Buttonhole Machine', 'MACHINE', 'UNIT'),
            ('Button Stitch Machine', 'MACHINE', 'UNIT'),
            ('Zigzag Machine', 'MACHINE', 'UNIT'),
            ('Blind Stitch Machine', 'MACHINE', 'UNIT'),
            ('Chain Stitch Machine', 'MACHINE', 'UNIT'),
            ('Cover Stitch Machine', 'MACHINE', 'UNIT'),
            ('Elastic Attaching Machine', 'MACHINE', 'UNIT'),
            ('Belt Loop Machine', 'MACHINE', 'UNIT'),
            ('Pattern Sewing Machine', 'MACHINE', 'UNIT'),
            ('Embroidery Machine', 'MACHINE', 'UNIT'),
            ('Aari Machine (optional)', 'MACHINE', 'UNIT'),
            ('Quilting Machine', 'MACHINE', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 16,
        'section': 'Finishing',
        'subsection': None,
        'items': [
            ('Steam Iron', 'MACHINE', 'UNIT'),
            ('Vacuum Iron Table', 'MACHINE', 'UNIT'),
            ('Boiler', 'MACHINE', 'UNIT'),
            ('Steam Generator', 'MACHINE', 'UNIT'),
            ('Thread Trimmer', 'MACHINE', 'UNIT'),
            ('Fabric Shaver', 'MACHINE', 'UNIT'),
            ('Lint Roller', 'TOOL', 'PIECE'),
            ('Spot Cleaning Gun', 'MACHINE', 'UNIT'),
            ('Stain Remover', 'CONSUMABLE', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 17,
        'section': 'Quality Control',
        'subsection': None,
        'items': [
            ('Measuring Tape', 'TOOL', 'PIECE'),
            ('QC Checklist', 'DOCUMENT', 'PIECE'),
            ('Needle Detector', 'TOOL', 'PIECE'),
            ('Metal Detector', 'TOOL', 'PIECE'),
            ('Shade Card', 'TOOL', 'PIECE'),
            ('Color Matching Box', 'TOOL', 'PIECE'),
            ('GSM Cutter', 'TOOL', 'PIECE'),
            ('Fabric Inspection Machine', 'TOOL', 'PIECE'),
            ('Defect Tags', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 18,
        'section': 'Packaging',
        'subsection': None,
        'items': [
            ('Polybags', 'MATERIAL', 'PIECE'),
            ('Zip Bags', 'MATERIAL', 'PIECE'),
            ('Garment Covers', 'MATERIAL', 'PIECE'),
            ('Tissue Paper', 'MATERIAL', 'PIECE'),
            ('Butter Paper', 'MATERIAL', 'PIECE'),
            ('Thank You Card', 'MATERIAL', 'PIECE'),
            ('Care Card', 'MATERIAL', 'PIECE'),
            ('Brand Story Card', 'MATERIAL', 'PIECE'),
            ('Warranty Card (if applicable)', 'MATERIAL', 'PIECE'),
            ('Gift Box', 'MATERIAL', 'PIECE'),
            ('Rigid Box', 'MATERIAL', 'PIECE'),
            ('Folding Box', 'MATERIAL', 'PIECE'),
            ('Corrugated Box', 'MATERIAL', 'PIECE'),
            ('Paper Bag', 'MATERIAL', 'PIECE'),
            ('Luxury Shopping Bag', 'MATERIAL', 'PIECE'),
            ('Cloth Bag', 'MATERIAL', 'PIECE'),
            ('Dust Bag', 'MATERIAL', 'PIECE'),
            ('Silica Gel', 'MATERIAL', 'PIECE'),
            ('Sticker Seal', 'MATERIAL', 'PIECE'),
            ('Security Seal', 'MATERIAL', 'PIECE'),
            ('Shipping Label', 'MATERIAL', 'PIECE'),
            ('Barcode', 'MATERIAL', 'PIECE'),
            ('Invoice', 'DOCUMENT', 'PIECE'),
            ('Courier Pouch', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 19,
        'section': 'Warehouse',
        'subsection': None,
        'items': [
            ('Garment Racks', 'ASSET', 'UNIT'),
            ('Shelves', 'ASSET', 'UNIT'),
            ('Hangers', 'ASSET', 'UNIT'),
            ('Size Dividers', 'ASSET', 'UNIT'),
            ('Storage Bins', 'ASSET', 'UNIT'),
            ('Pallets', 'ASSET', 'UNIT'),
            ('Trolleys', 'ASSET', 'UNIT'),
            ('Inventory Labels', 'ASSET', 'UNIT'),
            ('Barcode Scanner', 'MACHINE', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 20,
        'section': 'Retail Store',
        'subsection': None,
        'items': [
            ('Mannequins', 'ASSET', 'UNIT'),
            ('Trial Room Mirrors', 'ASSET', 'UNIT'),
            ('Display Tables', 'ASSET', 'UNIT'),
            ('Display Racks', 'ASSET', 'UNIT'),
            ('Cash Counter', 'ASSET', 'UNIT'),
            ('POS Machine', 'MACHINE', 'UNIT'),
            ('Billing Printer', 'MACHINE', 'UNIT'),
            ('Security Tags', 'ASSET', 'UNIT'),
            ('CCTV', 'MACHINE', 'UNIT'),
            ('Music System', 'ASSET', 'UNIT'),
            ('Lighting', 'ASSET', 'UNIT'),
            ('Steamers', 'MACHINE', 'UNIT'),
            ('Display Bust Forms', 'ASSET', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 21,
        'section': 'E-commerce',
        'subsection': None,
        'items': [
            ('Product Photography', 'SYSTEM', 'UNIT'),
            ('Flat Lay Setup', 'SYSTEM', 'UNIT'),
            ('Ghost Mannequin', 'SYSTEM', 'UNIT'),
            ('Lifestyle Photography', 'SYSTEM', 'UNIT'),
            ('Size Guide', 'SYSTEM', 'UNIT'),
            ('Product Videos', 'SYSTEM', 'UNIT'),
            ('SKU Codes', 'SYSTEM', 'UNIT'),
            ('Inventory Software', 'SYSTEM', 'UNIT'),
            ('ERP', 'SYSTEM', 'UNIT'),
            ('Website', 'SYSTEM', 'UNIT'),
            ('Mobile App', 'SYSTEM', 'UNIT'),
            ('Payment Gateway', 'SYSTEM', 'UNIT'),
            ('CRM', 'SYSTEM', 'UNIT'),
            ('OMS (Order Management)', 'SYSTEM', 'UNIT'),
            ('WMS (Warehouse Management)', 'SYSTEM', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 22,
        'section': 'Logistics',
        'subsection': None,
        'items': [
            ('Courier Bags', 'MATERIAL', 'PIECE'),
            ('Shipping Boxes', 'MATERIAL', 'PIECE'),
            ('Shipping Labels', 'MATERIAL', 'PIECE'),
            ('Barcode Labels', 'MATERIAL', 'PIECE'),
            ('Return Labels', 'MATERIAL', 'PIECE'),
            ('Packing Tape', 'MATERIAL', 'PIECE'),
            ('Bubble Wrap', 'MATERIAL', 'PIECE'),
            ('Stretch Film', 'MATERIAL', 'PIECE'),
            ('Fragile Stickers', 'MATERIAL', 'PIECE'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 23,
        'section': "Women's Clothing Categories",
        'subsection': None,
        'items': [
            ('Sarees', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Blouses', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Lehengas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Gowns', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Salwar Suits', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Kurtis', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Co-ord Sets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Dresses', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Tops', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Tunics', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Kaftans', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Skirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Palazzo Pants', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Shararas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Gararas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jeans', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Trousers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jackets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Blazers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Capes', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Nightwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Loungewear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Activewear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Innerwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Swimwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Maternity Wear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Bridal Wear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Indo-Western Wear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Ethnic Jackets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Dupattas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Stoles', 'PRODUCT_CATEGORY', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 24,
        'section': "Men's Clothing Categories",
        'subsection': None,
        'items': [
            ('Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('T-Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Polo Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jeans', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Trousers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Chinos', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Shorts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Cargo Pants', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Joggers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Hoodies', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Sweatshirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jackets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Blazers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Suits', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Waistcoats', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Sherwanis', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Kurtas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Nehru Jackets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Pathani Suits', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Dhotis', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Loungewear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Nightwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Innerwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Activewear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Swimwear', 'PRODUCT_CATEGORY', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 25,
        'section': "Boys' Clothing",
        'subsection': None,
        'items': [
            ('Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('T-Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Polo Shirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Shorts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jeans', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Trousers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Joggers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Hoodies', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jackets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('School Uniforms', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Ethnic Kurtas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Sherwanis', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Waistcoats', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Night Suits', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Innerwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Swimwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Rompers (toddlers)', 'PRODUCT_CATEGORY', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 26,
        'section': "Girls' Clothing",
        'subsection': None,
        'items': [
            ('Frocks', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Dresses', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Tops', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Skirts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Shorts', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Leggings', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jeans', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Kurtis', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Lehengas', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Gowns', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Party Wear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Ethnic Wear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Co-ord Sets', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Jumpsuits', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Nightwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Innerwear', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Rompers', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Onesies', 'PRODUCT_CATEGORY', 'UNIT'),
            ('Hair Accessories', 'PRODUCT_CATEGORY', 'UNIT'),
        ],
    },
    {
        'doc': 'APPAREL',
        'sequence': 27,
        'section': 'Customer Delivery',
        'subsection': None,
        'items': [
            ('Invoice', 'DOCUMENT', 'PIECE'),
            ('GST Bill', 'DOCUMENT', 'PIECE'),
            ('Warranty Card (if offered)', 'MATERIAL', 'PIECE'),
            ('Care Instructions', 'DOCUMENT', 'PIECE'),
            ('Brand Card', 'MATERIAL', 'PIECE'),
            ('Loyalty Card', 'MATERIAL', 'PIECE'),
            ('QR Code for Reviews', 'MATERIAL', 'PIECE'),
            ('Return Form', 'MATERIAL', 'PIECE'),
            ('Gift Wrap', 'MATERIAL', 'PIECE'),
            ('Courier Tracking', 'SYSTEM', 'UNIT'),
            ('Delivery Confirmation', 'DOCUMENT', 'PIECE'),
        ],
    },
]


def all_items():
    for group in CATALOG:
        for name, item_type, unit in group['items']:
            yield {
                'doc': group['doc'],
                'sequence': group['sequence'],
                'section': group['section'],
                'subsection': group['subsection'],
                'name': name,
                'item_type': item_type,
                'unit': unit,
            }
