"""
Django settings for boutique_crm project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Populate os.environ from a KEY=VALUE file, without overriding real env vars.

    Keeps credentials in a gitignored .env instead of in this file. Deployments
    (Render, Vercel) set real env vars and have no .env, so this is a no-op there.
    """
    if not path.exists():
        return
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip())


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-do-not-use-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a deploy that forgets to set it cannot serve tracebacks --
# with DEBUG on, any unauthenticated request that errors returns source paths and
# settings. Local development turns it back on via .env.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h]


# Application definition

SHARED_APPS = [
    'django_tenants',  # mandatory
    'tenants',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # No models of its own; required for the postgres-specific index types the
    # design library uses (GinIndex on spec_tags).
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

TENANT_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework.authtoken',
    'crm_api',
    'apps.production',
    'apps.activities',
    'apps.scheduling',
    'apps.design_studio',
    'apps.inventory',
    'apps.catalog',
]

INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'tenants.middleware.TenantHeaderMiddleware',  # header tenant switcher
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'boutique_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boutique_crm.wsgi.application'


# Only DB_PASSWORD is a secret. The project ref, region and username are public
# identifiers and keep defaults so a deploy that sets just DB_PASSWORD -- which is
# all the README ever asked for -- still connects.
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres.gbdabwahffdgdykbujpx'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'aws-1-ap-southeast-1.pooler.supabase.com'),
        # Port 5432 on the pooler host is Supabase's *session* pooler, and this
        # application cannot use the transaction pooler on 6543.
        #
        # django-tenants selects a tenant by issuing `SET search_path`, which is
        # session state. Under transaction pooling pgbouncer hands each
        # transaction to whichever server backend is free, so the search_path set
        # when the tenant was resolved need not still apply to the next query in
        # the same request. The query then runs against `public`.
        #
        # That is not theoretical: on 6543 this produced intermittent
        # `401 {"detail":"Invalid token."}` in production. `authtoken` is in both
        # SHARED_APPS and TENANT_APPS, so the token table exists in public *and*
        # in every tenant schema; a token written to the tenant schema simply is
        # not found when the lookup drifts to public. Measured against the live
        # service: 14 sequential requests all succeeded, while 12 concurrent
        # requests returned 9x200, 2x401 and 1x500 with the same token.
        #
        # Session pooling gives each client connection its own server backend for
        # the life of that connection, which is what makes search_path -- and
        # therefore tenant isolation -- hold.
        'PORT': os.environ.get('DB_PORT', '5432'),

        # Persistent connections, for two reasons.
        #
        # They are safe *because* of the session pooler above: the backend behind
        # a reused connection stays the same one, so the schema it is pointed at
        # stays true between requests. On the transaction pooler this same
        # setting was actively harmful -- Django believed the connection was
        # already on the tenant schema and skipped re-issuing the SET, while
        # pgbouncer had moved it to another backend underneath.
        #
        # They are also worth having: at 0 every request paid a fresh TCP
        # connect, TLS handshake and pooler auth against a database in another
        # region, which costs more than most of the queries the request then
        # makes. Holding connections burns pooler slots, so they are bounded
        # rather than unlimited -- under gunicorn.conf.py this process holds at
        # most workers * threads (2 * 4 = 8). Set DB_CONN_MAX_AGE=0 to return to
        # connect-per-request if the pooler ever reports slot exhaustion.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        # Kept from the transaction-pooler configuration. Server-side cursors are
        # no longer hazardous on a session pooler, but nothing in this codebase
        # relies on .iterator() streaming, so leaving it off costs nothing and
        # keeps the setting correct if HOST is ever pointed back at 6543.
        'DISABLE_SERVER_SIDE_CURSORS': True,
        'OPTIONS': {
            # Never let a request hang on the network; fail fast and visibly.
            'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
        },
    }
}

# Fallback to local development DB if USE_LOCAL_DB=True is set.
#
# The test runner defaults to local even when the variable is unset. Without this,
# `manage.py test` aims the whole suite at the shared Supabase database: it would
# CREATE and DROP a test_ database on the hosted instance, and when the pooler
# password is not in the environment it simply fails to connect, so every test
# errors before it runs. Neither outcome is what "run the tests" should mean.
# Set USE_LOCAL_DB=False explicitly to test against the remote database anyway.
_use_local_db = os.environ.get('USE_LOCAL_DB')
if _use_local_db is None and 'test' in sys.argv:
    _use_local_db = 'True'

if _use_local_db == 'True':
    DATABASES['default'].update({
        'NAME': 'boutique_crm',
        'USER': 'sanjaykumar',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    })

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# django_tenants re-issues `SET search_path` on *every* cursor by default, so a
# single view spent as many round trips announcing its schema as it did reading
# data -- the dashboard alone ran 11 of them out of 25 queries. Each one is a
# full round trip to the database, which is invisible against a local Postgres
# and dominates the response against a hosted one. Setting this makes the search
# path stick for the life of the connection, which is exactly the semantics we
# want: the tenant is resolved once per request in TenantHeaderMiddleware and
# never changes mid-request. Anything that *does* need another schema goes
# through schema_context, which resets the flag itself.
# DO NOT turn this on. It looks like free performance and it is not.
#
# django_tenants re-issues `SET search_path` on every cursor, which is roughly
# half the round trips of a typical request here (11 of the dashboard's 25
# queries). TENANT_LIMIT_SET_CALLS=True collapses those to one per connection,
# and it does hold up under plain request interleaving -- which is exactly what
# makes it tempting.
#
# It is unsafe because `SET` in Postgres is transactional. A ROLLBACK silently
# reverts search_path to the session default ("$user", public) while
# django_tenants' cached flag still says the path is set, so it never re-issues
# it. Every query after a rolled-back transaction then runs against the *public*
# schema instead of the tenant's -- reading or writing the wrong boutique's data
# rather than failing loudly. apps/catalog's tests catch this (18 errors, tables
# "missing" because the connection quietly fell back to public).
#
# Reduce round trips by issuing fewer queries instead; see DashboardView.
TENANT_LIMIT_SET_CALLS = False

TENANT_MODEL = 'tenants.BoutiqueTenant'
TENANT_DOMAIN_MODEL = 'tenants.Domain'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set CORS_ALLOWED_ORIGINS (comma-separated) in production to lock this down.
# Credentials stay off: the frontend authenticates with a token header, not cookies.
_cors_origins = [o for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o]
CORS_ALLOW_CREDENTIALS = False
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_origins
else:
    CORS_ALLOW_ALL_ORIGINS = True

from corsheaders.defaults import default_headers, default_methods
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-tenant-id',
]
CORS_ALLOW_METHODS = list(default_methods)


SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_KEY = os.environ.get('SUPABASE_KEY', '')
SUPABASE_BUCKET = os.environ.get('SUPABASE_BUCKET', 'boutique-crm')

# Uploads go to the local filesystem; the SupabaseStorage driver in crm_api/storage.py
# is bypassed because bucket RLS policies reject the publishable key.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Business endpoints require a token. Sign-up and login opt out explicitly
    # via permission_classes on their own views.
    # Not just IsAuthenticated: signed in is not the same as entitled. Every
    # business endpoint that does not name its own permission class gets the
    # role rules, so a new viewset is locked down by default rather than by
    # someone remembering. Sign-up and login opt out on their own views.
    'DEFAULT_PERMISSION_CLASSES': [
        'core.permissions.RolePermission',
    ],
}


# --- Customer tracking & messaging ---------------------------------------
# Where a customer's tracking link points. Messages are composed server-side
# with no request in hand, so the public origin has to be configured rather
# than derived. Set this to the deployed host or every link a customer receives
# points at localhost.
TRACKING_BASE_URL = os.environ.get('TRACKING_BASE_URL', 'http://localhost:8000')

# How customer messages are delivered. The default only writes them to the log
# and to CustomerMessage, so the communication history, the boutique toggle and
# the tracking links all work before any WhatsApp Business account exists.
# Point this at another callable taking a CustomerMessage to actually send.
CUSTOMER_MESSAGE_BACKEND = os.environ.get(
    'CUSTOMER_MESSAGE_BACKEND',
    'domains.orders.messaging.log_backend',
)


# --- AI Design Studio ---------------------------------------------------
# The studio's intelligence is pluggable. Left unset it uses a deterministic
# rule-based engine that needs no credentials and costs nothing, so design
# discovery works out of the box. Point this at another implementation of
# apps.design_studio.intelligence.base.DesignIntelligence to swap it.
DESIGN_STUDIO_INTELLIGENCE = os.environ.get(
    'DESIGN_STUDIO_INTELLIGENCE',
    'apps.design_studio.intelligence.rules.RuleBasedIntelligence',
)

# External design sources stay dormant until credentialed. Each is reported to
# the gallery as unavailable rather than failing a search.
DESIGN_STUDIO_PINTEREST_TOKEN = os.environ.get('DESIGN_STUDIO_PINTEREST_TOKEN', '')
DESIGN_STUDIO_GOOGLE_API_KEY = os.environ.get('DESIGN_STUDIO_GOOGLE_API_KEY', '')


