# Generated by Django 6.0.6 on 2026-09-09 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_design_parts_and_bottom_wear'),
        ('crm_api', '0029_alter_boutiquesettings_logo_and_more'),
        ('inventory', '0010_ordermaterialline_gathered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alteration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('alteration_type', models.CharField(choices=[('FREE_BOUTIQUE_FAULT', 'Free / Boutique Fault'), ('PAID_CLIENT_REQUEST', 'Paid / Customer Request')], db_index=True, default='PAID_CLIENT_REQUEST', max_length=50)),
                ('issue_description', models.TextField(blank=True, default='')),
                ('requested_adjustments', models.JSONField(blank=True, default=dict)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('inspection_adjustments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('INSPECTION', 'Inspection'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('QC', 'Quality Check'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=50)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteration_requests', to='crm_api.customer')),
                ('garment_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteration_requests', to='catalog.garmentjob')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteration_requests', to='crm_api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlterationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('CARD', 'Credit / Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('received_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_alteration_payments', to=settings.AUTH_USER_MODEL)),
                ('alteration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='alterations.alterationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlterationMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='PIECE', max_length=20)),
                ('recorded_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteration_material_lines', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_alteration_material_lines', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteration_material_lines', to='inventory.stockmovement')),
                ('alteration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='alterations.alterationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlterationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('performed_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteration_activities', to=settings.AUTH_USER_MODEL)),
                ('alteration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='alterations.alterationrequest')),
            ],
            options={
                'verbose_name_plural': 'Alteration activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlterationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('stage_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('sequence', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alteration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='alterations.alterationrequest')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alteration_tasks', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alterationrequest',
            index=models.Index(fields=['status', '-created_at'], name='alterations_status_3ff0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='alterationrequest',
            index=models.Index(fields=['customer', '-created_at'], name='alterations_custome_f3b2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='alterationrequest',
            index=models.Index(fields=['original_order', '-created_at'], name='alterations_origina_758d06_idx'),
        ),
        migrations.AddConstraint(
            model_name='alterationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('charge_amount__gte', 0)), name='alteration_charge_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='alterationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='alteration_amount_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='alterationpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='alteration_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='alterationpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('alteration_request', 'transaction_reference'), name='unique_alteration_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='alterationmaterialline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='alteration_material_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='alterationactivity',
            index=models.Index(fields=['alteration_request', '-timestamp'], name='alterations_alterat_bda03a_idx'),
        ),
        migrations.AddConstraint(
            model_name='alterationtask',
            constraint=models.UniqueConstraint(fields=('alteration_request', 'stage_key'), name='one_alteration_task_per_stage'),
        ),
    ]
