# Generated by Django 6.0.6 on 2026-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_for', models.JSONField(blank=True, default=list)),
                ('rollout_percent', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('modified_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(db_index=True, help_text='Username of the administrator. Stored as text, not a FK, so the entry outlives the account.', max_length=150)),
                ('action', models.CharField(choices=[('boutique.suspend', 'Boutique suspended'), ('boutique.reactivate', 'Boutique reactivated'), ('boutique.modules', 'Boutique modules changed'), ('user.deactivate', 'User deactivated'), ('user.activate', 'User activated'), ('user.revoke_token', 'User sessions revoked'), ('user.password_reset', 'Password reset triggered'), ('lead.update', 'Lead updated'), ('flag.change', 'Feature flag changed'), ('setting.change', 'Platform setting changed'), ('error.acknowledge', 'Error acknowledged'), ('error.resolve', 'Error resolved'), ('data.view', 'Boutique data viewed'), ('console.login', 'Console sign-in'), ('console.login_failed', 'Console sign-in failed')], db_index=True, max_length=40)),
                ('target', models.CharField(blank=True, db_index=True, max_length=255)),
                ('boutique', models.CharField(blank=True, db_index=True, max_length=63)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['boutique', '-created_at'], name='superadmin__boutiqu_3a9b15_idx'), models.Index(fields=['actor', '-created_at'], name='superadmin__actor_2d8eb4_idx'), models.Index(fields=['action', '-created_at'], name='superadmin__action_b790bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=40, unique=True)),
                ('exception_type', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=500)),
                ('boutique', models.CharField(blank=True, db_index=True, max_length=63)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='high', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=12)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='superadmin__status_74a52f_idx'), models.Index(fields=['severity', '-last_seen'], name='superadmin__severit_1d39a6_idx'), models.Index(fields=['boutique', '-last_seen'], name='superadmin__boutiqu_908b82_idx')],
            },
        ),
    ]
