# Generated by Django 6.0.6 on 2026-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_errorevent_boutiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('boutique.suspend', 'Boutique suspended'), ('boutique.reactivate', 'Boutique reactivated'), ('boutique.modules', 'Boutique modules changed'), ('user.deactivate', 'User deactivated'), ('user.activate', 'User activated'), ('user.revoke_token', 'User sessions revoked'), ('user.password_reset', 'Password reset triggered'), ('lead.update', 'Lead updated'), ('flag.change', 'Feature flag changed'), ('setting.change', 'Platform setting changed'), ('error.acknowledge', 'Error acknowledged'), ('error.resolve', 'Error resolved'), ('data.view', 'Boutique data viewed'), ('console.login', 'Console sign-in'), ('console.logout', 'Console sign-out'), ('console.login_failed', 'Console sign-in failed')], db_index=True, max_length=40),
        ),
    ]
