# Generated by Django 6.0.6 on 2026-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_access_link_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorevent',
            name='kind',
            field=models.CharField(choices=[('crash', 'Unhandled crash'), ('handled', 'Handled exception'), ('refusal', 'Refused by a platform control'), ('client', 'Client error'), ('frontend', 'Frontend crash')], db_index=True, default='crash', max_length=10),
        ),
        migrations.AddField(
            model_name='errorevent',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='errorevent',
            index=models.Index(fields=['kind', '-last_seen'], name='superadmin__kind_c229c6_idx'),
        ),
    ]
