# Generated by Django 6.0.6 on 2026-08-07 12:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_gown_suit_sherwani'),
        ('design_studio', '0012_designer_email_alter_designer_user'),
        ('inventory', '0005_seed_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='design_studio.designasset')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='catalog.garmenttemplate')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('FABRIC', 'Fabric'), ('LINING', 'Lining'), ('INTERLINING', 'Interlining'), ('EMBROIDERY', 'Embroidery material'), ('THREAD', 'Thread'), ('ACCESSORY', 'Accessory'), ('LABEL', 'Label'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], db_index=True, default='FABRIC', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Fixed quantity, used when no formula is given.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_formula', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], default='PIECE', max_length=20)),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_optional', models.BooleanField(default=False, help_text='Skipped unless the order asks for it.')),
                ('is_customer_supplied', models.BooleanField(default=False, help_text='Brought by the customer. Never reserved from boutique stock.')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.billofmaterials')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.catalogitem')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['sequence', 'role'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], max_length=20)),
                ('to_unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], max_length=20)),
                ('factor', models.DecimalField(decimal_places=6, help_text='One from_unit equals this many to_unit.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('template', 'design', 'version'), name='uniq_bom_version'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('inventory_item__isnull', False), ('catalog_item__isnull', False), ('is_customer_supplied', True), _connector='OR'), name='bom_line_names_a_material'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('item', 'from_unit', 'to_unit'), name='uniq_item_unit_conversion'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.CheckConstraint(condition=models.Q(('from_unit', models.F('to_unit')), _negated=True), name='unit_conversion_differs'),
        ),
    ]
