# Generated by Django 6.0.6 on 2026-08-07 16:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0020_boutiquesettings_design_approval_required'),
        ('inventory', '0007_remove_billofmaterials_uniq_bom_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FABRIC', 'Fabric'), ('BORDER', 'Border'), ('LACE', 'Lace'), ('ACCESSORY', 'Accessory'), ('EMBROIDERY', 'Embroidery material'), ('OTHER', 'Other')], db_index=True, default='FABRIC', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], default='METER', max_length=20)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('used_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('damaged_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_materials', to='crm_api.order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMaterialMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received from customer'), ('USED', 'Used in the garment'), ('RETURNED', 'Returned to customer'), ('DAMAGED', 'Damaged'), ('CORRECTION', 'Correction')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('user_name_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.customermaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterialPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RESERVED', 'Reserved'), ('IN_PRODUCTION', 'In production'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('packaging_deducted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='inventory.billofmaterials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plans', to='crm_api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('FABRIC', 'Fabric'), ('LINING', 'Lining'), ('INTERLINING', 'Interlining'), ('EMBROIDERY', 'Embroidery material'), ('THREAD', 'Thread'), ('ACCESSORY', 'Accessory'), ('LABEL', 'Label'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], db_index=True, default='FABRIC', max_length=20)),
                ('material_name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('PAIR', 'Pair'), ('ROLL', 'Roll'), ('PACKET', 'Packet'), ('BOX', 'Box'), ('SET', 'Set'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('STRING', 'String'), ('UNIT', 'Unit')], default='PIECE', max_length=20)),
                ('required_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('wasted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_customer_supplied', models.BooleanField(db_index=True, default=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('bom_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='inventory.bomline')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_material_lines', to='inventory.inventoryitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.ordermaterialplan')),
            ],
            options={
                'ordering': ['sequence', 'role'],
            },
        ),
        migrations.AddConstraint(
            model_name='ordermaterialplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'RESERVED', 'IN_PRODUCTION'])), fields=('order',), name='one_live_material_plan_per_order'),
        ),
    ]
