# Generated by Django 6.0.6 on 2026-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_ordermaterialline_garment_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterialline',
            name='gathered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermaterialline',
            name='gathered_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ordermaterialline',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
