# Generated by Django 6.0.6 on 2026-09-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_ordermaterialline_gathered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='legacy_fabric_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='ItemPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment', models.CharField(max_length=40)),
                ('section', models.CharField(blank=True, default='', max_length=60)),
                ('slot', models.CharField(blank=True, default='', max_length=60)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['garment', 'section', 'slot'],
                'indexes': [models.Index(fields=['garment', 'section', 'slot'], name='inventory_i_garment_1a12fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'garment', 'section', 'slot'), name='uniq_item_placement')],
            },
        ),
    ]
