# Generated by Django 6.0.6 on 2026-07-28 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_api', '0016_alter_customer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SHORTLISTED', 'Shortlisted'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('search_queries', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_design_boards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_boards', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_boards', to='crm_api.customer')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_board', to='crm_api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('upload', 'Team Upload'), ('favourite', 'Saved Favourite'), ('pinterest', 'Pinterest'), ('google', 'Google Images')], db_index=True, default='upload', max_length=32)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('designer', models.CharField(blank=True, default='', max_length=150)),
                ('garment_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('occasion', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('colour_palette', models.JSONField(blank=True, default=list)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('popularity', models.IntegerField(default=0)),
                ('is_favourite', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='design_asset_unique_external_ref')],
            },
        ),
        migrations.CreateModel(
            name='DesignBoardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('colour_palette', models.JSONField(blank=True, default=list)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('match_score', models.IntegerField(default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('tailor_instructions', models.TextField(blank=True, default='')),
                ('production_notes', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='design_studio.designboard')),
                ('production_notes_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_notes', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['position', '-match_score', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('board',), name='design_board_single_selection')],
            },
        ),
    ]
