# Generated by Django 6.0.6 on 2026-08-05 06:26

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_resync_templates'),
        ('design_studio', '0003_backfill_designers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designasset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designasset',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'Simple'), ('MODERATE', 'Moderate'), ('COMPLEX', 'Complex')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='designasset',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designasset',
            name='spec_tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='designasset',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='designasset',
            name='stitch_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated stitch time.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='designasset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='catalog.garmenttemplate'),
        ),
        migrations.AddField(
            model_name='designasset',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='designasset',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designasset',
            name='visibility',
            field=models.CharField(choices=[('BOUTIQUE', 'Whole boutique'), ('DESIGNER_ONLY', 'Designer only')], default='BOUTIQUE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['spec_tags'], name='design_asset_spec_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['status', 'template'], name='design_asset_status_template'),
        ),
    ]
