# Generated by Django 6.0.6 on 2026-08-06 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0009_link_gowns_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('season', models.CharField(blank=True, default='', help_text="Free text: 'Bridal 2026', 'Summer'.", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='design_studio.designer')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='designasset',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='design_studio.collection'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('designer', 'name'), name='collection_unique_per_designer'),
        ),
    ]
