# Generated by Django 6.0.6 on 2026-08-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0011_designapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Set once the designer has a login. Null means credit only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
