# Generated by Django 6.0.6 on 2026-08-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_garmentjob_base_price_garmentjob_customization_price_and_more'),
        ('crm_api', '0028_order_discount'),
        ('design_studio', '0013_designassignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designboarditem',
            name='design_board_single_selection',
        ),
        migrations.AddField(
            model_name='designboarditem',
            name='garment_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_items', to='catalog.garmentjob'),
        ),
        migrations.AddConstraint(
            model_name='designboarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('board', 'garment_job'), name='design_board_single_selection_per_garment'),
        ),
        migrations.AddConstraint(
            model_name='designboarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('garment_job__isnull', True), ('is_selected', True)), fields=('board',), name='design_board_single_selection'),
        ),
    ]
