# Generated by Django 6.0.6 on 2026-09-02 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0014_remove_designboarditem_design_board_single_selection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.CharField(db_index=True, default='overall', max_length=60)),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='design_studio.designasset')),
            ],
            options={
                'ordering': ['part', 'sequence', 'created_at'],
                'indexes': [models.Index(fields=['design', 'part'], name='design_image_by_part')],
            },
        ),
    ]
