# Generated by Django 6.0.6 on 2026-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_design_parts_and_bottom_wear'),
        ('crm_api', '0028_order_discount'),
        ('design_studio', '0016_gallery_to_design_images'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designboarditem',
            name='design_board_single_selection_per_garment',
        ),
        migrations.RemoveConstraint(
            model_name='designboarditem',
            name='design_board_single_selection',
        ),
        migrations.AddField(
            model_name='designboarditem',
            name='part',
            field=models.CharField(db_index=True, default='overall', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='designboarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('board', 'garment_job', 'part'), name='design_board_single_selection_per_garment'),
        ),
        migrations.AddConstraint(
            model_name='designboarditem',
            constraint=models.UniqueConstraint(condition=models.Q(('garment_job__isnull', True), ('is_selected', True)), fields=('board', 'part'), name='design_board_single_selection'),
        ),
    ]
