# Generated by Django 6.0.6 on 2026-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0017_remove_designboarditem_design_board_single_selection_per_garment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
