# Generated by Django 6.0.6 on 2026-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0018_designer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='catalogue',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
