# Generated by Django 6.0.6 on 2026-09-12 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_0009_add_jacket_0009_trim_common_basic'),
        ('crm_api', '0042_orderstage_verification_note'),
        ('design_studio', '0019_designasset_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('garment_type', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('uploaded', 'Uploaded'), ('drawn', 'Drawn')], db_index=True, default='uploaded', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_designs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_designs', to='crm_api.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_designs', to='crm_api.order')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_designs', to='catalog.garmenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
