# Generated by Django 6.0.6 on 2026-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_garmentjob_base_price_garmentjob_customization_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttemplate',
            name='design_parts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
