# Generated by Django 6.0.6 on 2026-09-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_jacket'),
        ('catalog', '0009_trim_common_basic'),
    ]

    operations = [
    ]
