# Generated by Django 6.0.6 on 2026-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_0009_add_jacket_0009_trim_common_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentjob',
            name='selections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
