# Generated by Django 6.0.6 on 2026-09-01 10:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_api', '0028_order_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name_snapshot', models.CharField(max_length=150)),
                ('staff_role_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('regular_minutes', models.PositiveIntegerField(default=0)),
                ('gross_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('open_session_count', models.PositiveIntegerField(default=0)),
                ('has_overlap', models.BooleanField(default=False)),
                ('session_breakdown', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records_approved', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['staff_name_snapshot'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('period_start',), name='payroll_period_unique_week'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_period_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('period', 'staff'), name='payroll_record_unique_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('gross_earnings__isnull', True), ('gross_earnings__gte', 0), _connector='OR'), name='payroll_record_gross_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate_snapshot__isnull', True), ('hourly_rate_snapshot__gte', 0), _connector='OR'), name='payroll_record_rate_not_negative'),
        ),
    ]
