# Generated by Django 6.0.6 on 2026-09-02 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0028_order_discount'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name_snapshot', models.CharField(max_length=150)),
                ('entry_type', models.CharField(choices=[('DEPOSIT_AGREED', 'Security deposit agreed'), ('DEPOSIT_RECOVERY', 'Security deposit recovered')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deposit_balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deposit_balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deposit_recovered',
            field=models.DecimalField(decimal_places=2, default=0, help_text="What was actually taken -- never more than the obligation outstanding, and never more than the week's gross.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deposit_scheduled',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What this week was due to recover -- the weekly terms, already limited to what is still owed.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deposit_unrecovered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Scheduled recovery this week could not collect.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_before_other_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('net_before_other_deductions__isnull', True), ('net_before_other_deductions__gte', 0), _connector='OR'), name='payroll_record_net_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_recovered__gte', 0)), name='payroll_record_deposit_recovered_not_negative'),
        ),
        migrations.AddField(
            model_name='staffledgerentry',
            name='payroll_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payroll.payrollrecord'),
        ),
        migrations.AddField(
            model_name='staffledgerentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffledgerentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='crm_api.tailor'),
        ),
        migrations.AddIndex(
            model_name='staffledgerentry',
            index=models.Index(fields=['staff', 'entry_type', 'created_at'], name='ledger_staff_type_time'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ledger_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'DEPOSIT_RECOVERY')), fields=('payroll_record',), name='ledger_one_recovery_per_payroll'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'DEPOSIT_RECOVERY'), ('payroll_record__isnull', False)), models.Q(('entry_type', 'DEPOSIT_RECOVERY'), _negated=True), _connector='OR'), name='ledger_recovery_names_its_payroll'),
        ),
    ]
