# Generated by Django 6.0.6 on 2026-09-02 05:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0028_order_discount'),
        ('payroll', '0003_backfill_deposit_agreements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_recovered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What was actually taken -- never more than the advance outstanding, never more than what the deposit left.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_scheduled',
            field=models.DecimalField(decimal_places=2, default=0, help_text="What the advance's weekly rule called for, limited to what was still outstanding on it.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_unrecovered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Scheduled advance recovery this week could not collect.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DEPOSIT_AGREED', 'Security deposit agreed'), ('DEPOSIT_RECOVERY', 'Security deposit recovered'), ('ADVANCE_ISSUED', 'Advance issued'), ('ADVANCE_RECOVERY', 'Advance recovered'), ('ADVANCE_CANCELLED', 'Advance cancelled')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name_snapshot', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_recorded', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='payroll.payrollrecord')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name_snapshot', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('issued_on', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_issued', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='crm_api.tailor')),
            ],
            options={
                'ordering': ['issued_on', 'created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_recovered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='payroll.staffadvance'),
        ),
        migrations.AddField(
            model_name='staffledgerentry',
            name='advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payroll.staffadvance'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('advance_recovered__gte', 0)), name='payroll_record_advance_recovered_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('net_payable__isnull', True), ('net_payable__gte', 0), _connector='OR'), name='payroll_record_net_payable_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'ADVANCE_RECOVERY')), fields=('payroll_record',), name='ledger_one_advance_recovery_per_payroll'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['ADVANCE_ISSUED', 'ADVANCE_RECOVERY', 'ADVANCE_CANCELLED']), _negated=True), ('advance__isnull', False), _connector='OR'), name='ledger_advance_rows_name_their_advance'),
        ),
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'ADVANCE_RECOVERY'), _negated=True), ('payroll_record__isnull', False), _connector='OR'), name='ledger_advance_recovery_names_its_payroll'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payout_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_recovery__gte', 0)), name='advance_weekly_not_negative'),
        ),
    ]
