# Generated by Django 6.0.6 on 2026-09-02 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0028_order_discount'),
        ('payroll', '0004_advances_payouts_net_payable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'ADVANCE_CANCELLED')), fields=('advance',), name='ledger_one_cancel_per_advance'),
        ),
    ]
